config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, only: [:show, :edit, :update, :destroy]
  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'static/index'

  
  constraints Clearance::Constraints::SignedIn.new do
    root to: 'users#show', as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: 'static#index'
  end

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

end

app/models/authentication.rb
    class Authentication < ActiveRecord::Base

     belongs_to :user

      def self.create_with_omniauth(auth_hash)
        create! do |auth|
          auth.provider = auth_hash["provider"]
          auth.uid = auth_hash["uid"]
          auth.token = auth_hash["credentials"]["token"]
        end
      end

      def update_token(auth_hash)
        self.token = auth_hash["credentials"]["token"]
        self.save
      end

    end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  has_many :authentications, :dependent => :destroy

  def new_token
  	SecureRandom.urlsafe_base64
  end

  def self.create_with_auth_and_hash(authentication,auth_hash)
    create! do |u|
   
      u.first_name = auth_hash["info"]["first_name"]
      u.email = auth_hash["extra"]["raw_info"]["email"]
      u.encrypted_password = u.new_token
      u.remember_token = u.new_token
      u.authentications<<(authentication)
    end
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def password_optional?
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
 class SessionsController < Clearance::SessionsController

      def create_from_omniauth
        auth_hash = request.env["omniauth.auth"]

        authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) || Authentication.create_with_omniauth(auth_hash)
        if authentication.user
          user = authentication.user 
          authentication.update_token(auth_hash)
          @next = root_url
          @notice = "Signed in!"
        else
          user = User.create_with_auth_and_hash(authentication,auth_hash)
          @next = root_url #edit_user_path(user)   
          @notice = "User created - confirm or edit details..."
        end
        sign_in(user)
        redirect_to @next, :notice => @notice
      end
    end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  	@user = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

	def show
		@user = User.new(params[:user])
	end

	private 
	def user_from_params
		user_params = params[:user] || Hash.new
		first_name = user_params.delete(:first_name)
		last_name = user_params.delete(:last_name)
		gender = user_params.delete(:gender)
		birthdate = user_params.delete(:birthdate)
		contact_num = user_params.delete(:contact_num)
		description = user_params.delete(:description)
		country = user_params.delete(:country)
		email = user_params.delete(:email)
		password = user_params.delete(:password)

		# assigned those data into Clearance object 
		Clearance.configuration.user_model.new(user_params).tap do |user|
			user.first_name = first_name
			user.last_name = last_name
			user.gender = gender
			user.birthdate = birthdate
			user.contact_num = contact_num
			user.description = description
			user.country = country
			user.email = email
			user.password = password
		end
	end

	# sanitize the user_params to allow these data field to store in the database
	def permit_params
		params.require(:user).permit(:first_name, :last_name, :gender, :birthdate, :contact_num, :description, :country, :email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pairbnb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <% if signed_in? %>
 
      <%= button_to 'Sign out', sign_out_path, method: :delete %>

    <% else %>
    	      <%= link_to 'Sign in', sign_in_path %>
    	      

    <% end %>


    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

<div class="first-name-field">
  <%= form.label :first_name %>
  <%= form.text_field :first_name%>
</div>

<div class="last-name-field">
  <%= form.label :last_name %>
  <%= form.text_field :last_name%>
</div>

<div class="birthdate-field">
  <%= form.label :birthdate %>
  <%= form.date_field :birthdate %>
</div>

<div class="contact_num-field">
  <%= form.label :contact_num %>
  <%= form.telephone_field :contact_num %>
</div>

<div class="description-field">
  <%= form.label :description %>
  <%= form.text_area :description %>
</div>

<div class="country-field">
  <%= form.label :country %>
  <%= form.country_select :country %>
</div>

<div class="password-field">
  <%= form.label :gender%>
  <%= form.select :gender, options_for_select([["Male", "M"],["Female", "F"]])%>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

     <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div> 
  <% end %>
</div>

app/views/users/show.html.erb
<p> 
<strong>First Name: </strong> 
<%=current_user.first_name%>
</p>

<p>
<strong>Last Name: </strong> 
<%=current_user.last_name%>
</p>

<p> 
<strong>Email: </strong> 
<%=current_user.email%>
</p>

<p> 
<strong>Gender: </strong> 
<%=current_user.gender%>
</p>

<p> 
<strong>Nationality: </strong> 
<%=current_user.country%>
</p>